title: Enkhbold Ochirbat
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
include: ['_pages']
collections:
  books:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
